// Course: CS 12 spring quarter , 2010
//
// First Name: Christopher
// Last Name: Wong
// Login id: wongc
// email address: cwong030@student.ucr.edu
// Student id: 860 923 521
//
// Lecture Section: 002
// Lab Section: 023
// TA: A. Muzo
//
// Assignment: LAB 6
//
// I hereby certify that the code in this file
// is ENTIRELY my own original work.
//========================================================================

//square interface file

/****DO NOT EDIT THIS FILE****/

#ifndef __LSquare_H__
#define __LSquare_H__

#include "jrectangle.h"

class JSquare : public JRectangle
{
 public:
  JSquare();
  JSquare(Point, double);
  virtual JShape * make_shape(Point) const;
};

#endif
